---
title: "2. Exploratory Data Analysis. Ejemplos"
date: "Febrero 2025"
output: 
  html_document:
    toc: true
    toc_depth: 1
    theme: cerulean
---


<style>
body {
text-align: justify}
</style>

<style type="text/css">
body{/*Normal*/
     font-size: 20px;
}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(discrtr) # A companion package for the book Introduction to Discrete Choice Analysis with `R`
library(mlogit) # Multinomial Logit Models
library(readr) # Read Rectangular Text Data



library(gplots) # Various R Programming Tools for Plotting Data
library(ggmosaic) # Mosaic Plots in the 'ggplot2' Framework
library(treemapify)
library(ggridges)
library(ggalluvial)
library(plotly)
```




```{r}
data("mc_commute_wide")
glimpse(mc_commute_wide)
```
```{r}
ggplot(mc_commute_wide)+
  geom_bar(aes(shelter_good_quality, fill=gender), color="black")+
  theme_bw()
```


```{r}
mc_commute_wide |> group_by(choice) |> summarize(n = n()) |> 
ggplot(aes(fill = choice, area = n)) +
  geom_treemap() +
  labs(title = "Trips by mode", fill="Mode")
```




```{r}
ggplot(mc_commute_wide)+
  geom_bar(aes(choice, fill=choice), color="black", show.legend = FALSE)+
  theme_bw()
```





```{r}
mc_commute_alluvia <- mc_commute_wide |> 
  select(gender, vehind, choice) |> 
  group_by(gender, vehind, choice) |> 
  summarize(frequency = n(), .groups = "drop")
```



```{r}
mc_commute_alluvia |> 
  ggplot(aes(y = frequency, axis1 = gender, axis2 = vehind, axis3 = choice)) +
  geom_alluvium(aes(fill = choice), width = 1/3, color = "black") +
  geom_stratum(width = 1/3, fill = "black", color = "grey") +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), color = "white", size = 3) +
  scale_x_discrete(limits = c("Gender", "vehind", "Choice"), expand = c(.05, .05)) +
  scale_fill_brewer(type = "qual", palette = "Spectral") + 
  theme_minimal()
```



```{r}
ggplot(mc_commute_wide)+
  geom_point(aes(time.Cycle, time.Car, color=choice))+
  xlim(0,20)+
  ylim(0,25)+
  theme_bw()
```







